// Package auth holds Alex Messages's authentication primitives.
//
// Passwords are hashed with scrypt (RFC 7914); each hash stores its salt and
// parameters inline so verification needs no separate config. Sessions are
// opaque random tokens kept in the database and set on the client as HttpOnly
// cookies.
package auth

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"

	"golang.org/x/crypto/scrypt"

	"alexmessage/internal/db"
)

// scrypt parameters — RFC 7914 recommended for interactive logins.
const (
	scryptN   = 1 << 14
	scryptR   = 8
	scryptP   = 1
	scryptLen = 32
	saltLen   = 16

	// SessionTTLSeconds is the lifetime of an issued session (30 days).
	SessionTTLSeconds = 30 * 24 * 60 * 60

	UserCookie  = "am_session"
	AdminCookie = "am_admin_session"
)

var usernameRE = regexp.MustCompile(`^[a-zA-Z0-9_.-]{3,32}$`)

// ---------- password hashing ----------

// HashPassword returns a self-describing scrypt hash string.
func HashPassword(password string) (string, error) {
	salt := make([]byte, saltLen)
	if _, err := rand.Read(salt); err != nil {
		return "", err
	}
	derived, err := scrypt.Key([]byte(password), salt, scryptN, scryptR, scryptP, scryptLen)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("scrypt$%d$%d$%d$%s$%s",
		scryptN, scryptR, scryptP, hex.EncodeToString(salt), hex.EncodeToString(derived)), nil
}

// VerifyPassword checks a password against a stored scrypt hash. It never panics.
func VerifyPassword(password, stored string) bool {
	parts := strings.Split(stored, "$")
	if len(parts) != 6 || parts[0] != "scrypt" {
		return false
	}
	n, err1 := strconv.Atoi(parts[1])
	r, err2 := strconv.Atoi(parts[2])
	p, err3 := strconv.Atoi(parts[3])
	salt, err4 := hex.DecodeString(parts[4])
	expected, err5 := hex.DecodeString(parts[5])
	if err1 != nil || err2 != nil || err3 != nil || err4 != nil || err5 != nil {
		return false
	}
	derived, err := scrypt.Key([]byte(password), salt, n, r, p, len(expected))
	if err != nil {
		return false
	}
	return subtle.ConstantTimeCompare(derived, expected) == 1
}

// ---------- session tokens ----------

// IssueSession creates a session row and returns its token and expiry.
func IssueSession(userID int, scope string) (string, int64, error) {
	token, err := randomToken(32)
	if err != nil {
		return "", 0, err
	}
	expiresAt := db.NowTS() + SessionTTLSeconds
	if err := db.CreateSession(token, userID, expiresAt, scope); err != nil {
		return "", 0, err
	}
	return token, expiresAt, nil
}

// ResolveSession maps a token to its approved user, enforcing scope and admin
// requirements. Returns nil when the token is missing, invalid, or unauthorized.
func ResolveSession(token string, requiredScope string) *db.User {
	if token == "" {
		return nil
	}
	sess, err := db.GetSession(token)
	if err != nil || sess == nil {
		return nil
	}
	if requiredScope != "" && sess.Scope != requiredScope {
		return nil
	}
	user, err := db.GetUserByID(sess.UserID)
	if err != nil || user == nil {
		return nil
	}
	if user.Status != "approved" {
		return nil
	}
	if requiredScope == "admin" && !user.IsAdmin {
		return nil
	}
	return user
}

// randomToken mirrors Python's secrets.token_urlsafe(n): n random bytes encoded
// as unpadded URL-safe base64.
func randomToken(n int) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// ---------- validation ----------

// NormalizeUsername lowercases and trims a username.
func NormalizeUsername(s string) string {
	return strings.ToLower(strings.TrimSpace(s))
}

func ValidUsername(s string) bool {
	return usernameRE.MatchString(s)
}

func ValidPassword(s string) bool {
	return len(s) >= 8 && len(s) <= 128
}

// ---------- admin bootstrap ----------

// BootstrapAdmin creates the seed admin account if no admin exists yet.
//
// Reads ADMIN_USERNAME (default "admin") and ADMIN_PASSWORD from the
// environment. If ADMIN_PASSWORD is unset, a random one is generated and
// printed to stderr exactly once at startup.
func BootstrapAdmin() error {
	n, err := db.CountAdmins()
	if err != nil {
		return err
	}
	if n > 0 {
		return nil
	}

	username := NormalizeUsername(os.Getenv("ADMIN_USERNAME"))
	if username == "" {
		username = "admin"
	}
	password := os.Getenv("ADMIN_PASSWORD")
	autoGenerated := false
	if password == "" {
		password, err = randomToken(12)
		if err != nil {
			return err
		}
		autoGenerated = true
	}

	hash, err := HashPassword(password)
	if err != nil {
		return err
	}

	var uid int
	existing, err := db.GetUserByUsername(username)
	if err != nil {
		return err
	}
	if existing != nil {
		if err := db.SetPassword(existing.ID, hash); err != nil {
			return err
		}
		if err := db.SetAdmin(existing.ID, true); err != nil {
			return err
		}
		if err := db.UpdateUserStatus(existing.ID, "approved"); err != nil {
			return err
		}
		uid = existing.ID
	} else {
		uid, err = db.CreateUser(username, hash, "Admin", "approved", true)
		if err != nil {
			// Another process may have won the race; pick up its row.
			again, gerr := db.GetUserByUsername(username)
			if gerr != nil || again == nil {
				return err
			}
			if err := db.SetAdmin(again.ID, true); err != nil {
				return err
			}
			if err := db.UpdateUserStatus(again.ID, "approved"); err != nil {
				return err
			}
			uid = again.ID
		}
	}

	msg := fmt.Sprintf("[alex-messages] admin account ready: username=%q id=%d", username, uid)
	if autoGenerated {
		msg += fmt.Sprintf("  password=%q  (set ADMIN_PASSWORD env var to fix one)", password)
	}
	fmt.Fprintln(os.Stderr, msg)
	return nil
}
